export const dummyBookData = [
    { title: "Whispering Pines", author: "Amanda White", price: 18.99, publicationYear: 2020, },
    { title: "Eternal Twilight", author: "Robert Davis", price: 22.50, publicationYear: 2010 },
    { title: "Mystic Dreams", author: "Olivia Taylor", price: 14.95, publicationYear: 2001 },
    { title: "Silent Echo", author: "Christopher Green", price: 19.99, publicationYear: 2021 },
    { title: "Enchanted Waters", author: "Jessica Turner", price: 16.75, publicationYear: 2022 },
    { title: "Lost in Time", author: "Benjamin Walker", price: 20.50, publicationYear: 2005 },
    { title: "Crimson Horizon", author: "Rachel Adams", price: 24.99, publicationYear: 2003 },
    { title: "Moonlit Serenade", author: "Daniel Harris", price: 15.25, publicationYear: 2004 },
    { title: "Wandering Souls", author: "Megan Smith", price: 21.95, publicationYear: 2020 },
    { title: "Starlight Symphony", author: "Jonathan Miller", price: 17.50, publicationYear: 2004 },
    { title: "Sapphire Skies", author: "Emma Johnson", price: 23.75, publicationYear: 2020 },
    { title: "Secrets of the Ancients", author: "William Carter", price: 19.25, publicationYear: 2020 },
    { title: "Dancing Shadows", author: "Sophia Clark", price: 16.99, publicationYear: 2005 },
    { title: "Whirlwind of Destiny", author: "Nathan Turner", price: 25.50, publicationYear: 2020 },
    { title: "Echoes of the Past", author: "Grace Walker", price: 14.50, publicationYear: 2020 },
    { title: "Twilight Reverie", author: "Andrew White", price: 18.50, publicationYear: 2005 },
    { title: "Ripples in Time", author: "Lily Martin", price: 20.99, publicationYear: 2020 },
    { title: "Celestial Harmony", author: "Christopher Turner", price: 22.95, publicationYear: 2007 },
    { title: "Shadows of Tomorrow", author: "Hannah Baker", price: 15.99, publicationYear: 2020 },
    { title: "Serenade of Stars", author: "David Harris", price: 17.95, publicationYear: 2009 },
    { title: "Emerald Dreams", author: "Olivia Turner", price: 24.50, publicationYear: 2006 },
    { title: "Whispers in the Forest", author: "Matthew Green", price: 19.75, publicationYear: 2020 },
    { title: "Ephemeral Embrace", author: "Emily Walker", price: 16.50, publicationYear: 2020 },
    { title: "Chasing Fireflies", author: "Ethan Taylor", price: 23.99, publicationYear: 2013 },
    { title: "Crimson Moonlight", author: "Isabella Turner", price: 21.50, publicationYear: 2008 },
    { title: "Beyond the Horizon", author: "Michael Davis", price: 15.75, publicationYear: 2020 },
    { title: "Harmony's Song", author: "Sophia Adams", price: 18.25, publicationYear: 2020 },
    { title: "Enigma of Eternity", author: "Daniel Turner", price: 20.50, publicationYear: 2018 },
    { title: "Twilight Whispers", author: "Rachel Miller", price: 22.99, publicationYear: 2009 },
    { title: "Sapphire Dreams", author: "Benjamin Harris", price: 17.25, publicationYear: 2020 },
    { title: "Echoes of Enchantment", author: "Grace Turner", price: 24.95, publicationYear: 2000 },
    { title: "Stardust Symphony", author: "Andrew Miller", price: 19.50, publicationYear: 2014 },
    { title: "Whispering Winds", author: "Emma Turner", price: 15.99, publicationYear: 1999 },
    { title: "Eternal Embers", author: "Jonathan Smith", price: 23.50, publicationYear: 2020 },
    { title: "Moonlit Melody", author: "Lily Harris", price: 16.75, publicationYear: 2020 },
    { title: "Mystical Shadows", author: "Christopher Adams", price: 21.99, publicationYear: 2011 },
    { title: "Crimson Cascade", author: "Olivia Miller", price: 18.50, publicationYear: 2019 },
    { title: "Serenity's Echo", author: "Nathan Smith", price: 22.95, publicationYear: 2013 },
    { title: "Starlight Serenade", author: "Hannah Turner", price: 15.50, publicationYear: 2020 },
    { title: "Enchanted Reverie", author: "Daniel Adams", price: 20.99, publicationYear: 1999 },
    { title: "Echoes of Destiny", author: "Grace Harris", price: 24.50, publicationYear: 2020 },
    { title: "Celestial Cascade", author: "Benjamin Turner", price: 19.75, publicationYear: 2000 },
    { title: "Silent Symphony", author: "Emma Smith", price: 17.25, publicationYear: 2006 },
    { title: "Wandering Stars", author: "Christopher Turner", price: 21.50, publicationYear: 2012 },
    { title: "Mystic Moonlight", author: "Olivia Adams", price: 16.99, publicationYear: 2020 },
    { title: "Sapphire Symphony", author: "Nathan Harris", price: 23.25, publicationYear: 2014 },
    { title: "Whispers of Wisdom", author: "Sophia Turner", price: 18.95, publicationYear: 2017 },
    { title: "Eternal Echo", author: "Matthew Adams", price: 22.50, publicationYear: 2020 },
    { title: "Moonlit Mirage", author: "Lily Turner", price: 15.75, publicationYear: 2015 },
    { title: "Harmony's Embrace", author: "Andrew Harris", price: 19.99, publicationYear: 2001 }
] as const;